ChatBot/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from chat_ml import urls
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('chat_ml.urls')),
]

chat_ml/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chatapp'

urlpatterns = [
url(r'^$', views.googleapi, name='home'),

        ]

chat_ml/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return self.name



class Jobs(models.Model):
    name=models.CharField(max_length=30)
    desc=models.CharField(max_length=1000)
    expmax=models.IntegerField()
    skillset=models.ManyToManyField(Skill)

    def __str__(self):
        return self.name

chat_ml/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponse,render_to_response
from django.shortcuts import render, redirect
from sklearn.feature_extraction.text import CountVectorizer

from .Model.googleapimod import *
from random import choice
from string import ascii_uppercase
import json
# Create your views here.

def googleapi(request):

    if 'key' not in request.session:
        request.session['key']=''.join(choice(ascii_uppercase) for i in range(10))
    if request.is_ajax():
        q=request.POST['query']
        ans=getResult(q,request.session['key'])
        if ans['type']=='speech' and 'skills' in ans['res']:
            s = Skill.objects.all()
            ans['res']+=" You can choose from- "+ ', '.join([i.name.replace('_',' ').title() for i in s])

        return HttpResponse(json.dumps(ans), content_type="application/json")

    return render(request,'chat_ml/chatengine.html')

chat_ml/templates/chat_ml/chatengine.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chatbot</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            console.log("{{ name }}")
            var $div=$("<div>",{'class':"answer",style:"color:white; background-color:blue;padding: 25px;margin: 25px;max-width:60%;clear:both;float:left;border-radius: 25px"});
                $div.text("Hey , I'll try to provide you current openings matched with your relevant skill set."+
                "You can start by asking me about how to get a job at Sopra Steria")
            $('#chatbox').append($div);

            $(document).on('click','.Jobs',function (e)  {
                e.preventDefault()

                var $desc=$("<div>",{id:"desc",'class':"answer",style:"color:white; background-color:blue;padding: 25px;margin: 25px;max-width:60%;clear:both;float:left;border-radius: 25px"});
                $desc.text($(this).data('desc'));
                $('#chatbox').append($desc);
                window.scrollTo(0,document.body.scrollHeight);

            });


           $('#sub').click(function(e){
               e.preventDefault();
              q=$('#query').val();
              $('#query').val("");
                var $div=$("<div>",{'class':"question",style:"color:black; background-color:#edeeef;font-size:15px;padding: 25px;margin: 25px;max-width:60%;clear:both;float:right;border-radius: 25px"});
                $div.text(q);
               $('#chatbox').append($div);

              $.ajax({
                type: 'POST',
                url: $(this).attr('href'),
                data: {
                    query:q,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function (data) {
                    console.log(data)


                    if(data['type']=='speech'){
                        var $speechdiv=$("<div>",{'class':"answer",style:"color:white; background-color:blue;padding: 25px;margin: 25px;max-width:60%;clear:both;float:left;border-radius: 25px"});
                        $speechdiv.text(data['res'])
                        $('#chatbox').append($speechdiv)

                    }
                    else if(data['type']=='jobs'){

                        for(var i=0;i<data['res'].length;i++){
                            var $jobdiv=$("<div>",{id:"job"+i,"class":'Jobs answer',style:"color:white; background-color:blue;padding: 25px;margin: 25px;max-width:60%;clear:both;float:left;border-radius: 25px"});
                            var $jobname=$("<div>");
                            $jobname.text(data['res'][i]['jobname']);
                            var $skills=$("<div>",{id:"skill"+i});
                            $skills.text("Relevant Skills- "+data['res'][i]['skill']);
                            $jobdiv.append($jobname);
                            $jobdiv.append($skills);
                            $jobdiv.data('desc',data['res'][i]['jobdesc']);
$                           ('#chatbox').append($jobdiv)
                        }
                        var $div=$("<div>",{'class':"answer",style:"color:white; background-color:blue;padding: 25px;margin: 25px;max-width:60%;clear:both;float:left;border-radius: 25px"});

                        $div.text("You can click on the Job Profile for more details.");
                        $('#chatbox').append($div)



                    }


                    console.log("{{ manu }}")

                    window.scrollTo(0,document.body.scrollHeight);
                }

});
           });


        });
    </script>

</head>
<body >
<div id="chatbox" >

</div>
<div id="form" style="position:fixed;bottom:0px;width: 100%;height: 6%" >
<form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="query" id="query" style="float: left;width: 80%;height: 100%" autocomplete="off">
    <button type="submit" style="float: right;width: 20%;height: 100%" href="{% url 'chatapp:home' %}" id="sub">Send</button>
</form>
</div>

</body>


</html>